export const hardcodeData = [
  //Producto 1  
  {
    descripcion: 'Alcohol etílico con el 63%, con una mezcla especial como Vitamina “E”, aloe y humectantes. Ayudando a eliminar los gérmenes, bacterias y virus, dejando sus manos limpias, ',
    nombreProducto: 'Gel Antibacterial Instant Clean x 1000 ml',
    stock: '1000',
    etiquetas: 'No',
    precio: 26.50,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/1.jpg`,
    idCategoria: 'null',
  },
  //Producto 2
  {
    descripcion: 'Contiene Vitamina C 1000mg y Zinc 10mg. Sin azúcar.Sin lactosa. Sin gluten. Sin azúcar. Sin preservantes. Sabor naranja.Fácil de tomar y rápida absorción ...',
    nombreProducto: 'Vitamina C + Zinc.Efervescente Sabor Naranja',
    stock: '1000',
    etiquetas: 'No',
    precio: 13.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/2.jpg`,
    idCategoria: 'null',
  },
  //producto 3 
  {
    descripcion: 'Reduce la fiebre y alivia temporalmente el dolor de cabeza, migraña, dolor de osteoartritis, dolor dental, dolor luego de procedimientos dentales, dolores musculares, dolor de garganta y dolor menstrual.',
    nombreProducto: 'Panadol Forte Tableta',
    stock: '1000',
    etiquetas: 'No',
    precio: 1.77,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/3.jpg`,
    idCategoria: 'null',
  },
  //producto 4 
  {
    descripcion: 'Vick VapoRub es un ungüento que combina mentol, eucalipto y alcanfor en un ungüento, que ayuda a descongestionar las vías respiratorias, calmar la tos y alivio temporal de dolores musculares menores.',
    nombreProducto: 'Vick Vaporub Ungüento tópico',
    stock: '1000',
    etiquetas: 'No',
    precio: 14.30,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/4.jpg`,
    idCategoria: 'null',
  },
  //producto 5 
  {
    descripcion: 'Indicado para el alivio de los síntomas de flatulencia. exceso de as; alivio de la hinchazon/presión/dolor/llenura. ...',
    nombreProducto: 'Gaseovet 80mg/ml Suspensión Gotas Sabor Fresa',
    stock: '1000',
    etiquetas: 'No',
    precio: 18.50,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/5.jpg`,
    idCategoria: 'null',
  },
  //producto 6 
  {
    descripcion: 'Tratamiento de prevención cardiovascular original, ayuda a prevenir formación de coágulos, ayuda en la prevención de un segundo infarto y de accidentes cerebro-vasculares isquémicos.',
    nombreProducto: 'Aspirina 100mg Tableta',
    stock: '1000',
    etiquetas: 'No',
    precio: 46.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/6.jpg`,
    idCategoria: 'null',
  },
  //producto 7 
  {
    descripcion: 'Alivia la fiebre y el dolor leve a moderado incluyendo: dolor de cabeza, dolor muscular, dolor de garganta, dolor musculo esquelético, dolor de la dentición, ...',
    nombreProducto: 'Panadol 160mg/5ml Jarabe',
    stock: '1000',
    etiquetas: 'No',
    precio: 14.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/7.jpg`,
    idCategoria: 'null',
  },
  //producto 8 
  {
    descripcion: 'Bismutol es un protector estomacal de acción múltiple indicado para el alivio de 3 problemas estomacales: pesadez, acidez e indigestión.',
    nombreProducto: 'Bismutol Suspensión x 340 ml',
    stock: '1000',
    etiquetas: 'No',
    precio: 26.20,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/8.jpg`,
    idCategoria: 'null',
  },
  //producto 9 
  {
    descripcion: 'Aguja para lapicero de insulina para usarse con PEN o aplicador de insulina en cárpula o dispositivos ...',
    nombreProducto: 'Aguja para Lapicero de Insulina BD 32 x 4 mm Easy Flow x 20 Aguja',
    stock: '1000',
    etiquetas: 'No',
    precio: 23.20,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/9.jpg`,
    idCategoria: 'null',
  },
  //producto 10 
  {
    descripcion: 'La mascarilla desechable de 3 pliegues te ayuda con la protección contra agentes externos y reduce el riesgo de contaminación.',
    nombreProducto: 'Mascarilla Desechable 3 Pliegues - Caja 50 UN',
    stock: '1000',
    etiquetas: 'No',
    precio: 14.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/10.jpg`,
    idCategoria: 'null',
  },
  //producto 11 
  {
    descripcion: 'Con canales de aire que permiten que el aire fluya libremente dentro del pañal, manteniendo ...',
    nombreProducto: 'Pampers Confort Sec M x 62 Pañales',
    stock: '1000',
    etiquetas: 'No',
    precio: 42.70,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/11.jpg`,
    idCategoria: 'null',
  },
  //producto 12
  {
    descripcion: 'El talco Isana tiene su fórmula con triclosán y almidón de maíz que contienen propiedades ...',
    nombreProducto: 'Talco para Pies Isana x 60 g + Talco x 60 g',
    stock: '1000',
    etiquetas: 'No',
    precio: 9.70,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/12.jpg`,
    idCategoria: 'null',
  },
  //producto 13 
  {
    descripcion: 'Eucerin Hyaluron-Filler + Elasticity Crema Cuidado de Noche fortalece la piel, mejora la elasticidad y tiene un efecto relleno anti-arrugas. Su fórmula exclusiva e innovadora ofrece múltiples beneficios contra los signos del envejecimiento. La piel se siente firme, suave, fresca y radiante.',
    nombreProducto: 'Crema Antiarrugas Eucerin Hyaluron-Filler',
    stock: '1000',
    etiquetas: 'No',
    precio: 155.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/13.jpg`,
    idCategoria: 'null',
  },
  //producto 14 
  {
    descripcion: 'Úsalos todos los días como parte de rutina de higiene diaria. Adhesivo en la base, que mantiene el protector en su sitio. Cámbiate frecuentemente el protector para evitar malos olores y posibles irritaciones.',
    nombreProducto: 'Protectores Diarios Nosotras Normal x 120 Unidades',
    stock: '1000',
    etiquetas: 'No',
    precio: 19.20,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/14.jpg`,
    idCategoria: 'null',
  },
  //producto 15 
  {
    descripcion: 'Empaque individual para mejor conservación y manejo, pequeño tamaño de muestra de 0.6 µl, lectura de resultados en 5 segundos no necesita codificación Las lancetas junto con el dispositivo de punción, proporcionan un medio portátil y cómodo para obtener ...',
    nombreProducto: 'Freestyle Pack 50 Tiras + 100 Lancetas',
    stock: '1000',
    etiquetas: 'No',
    precio: 139.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/15.jpg`,
    idCategoria: 'null',
  },
  //producto 16 
  {
    descripcion: 'Glucerna® es nutrición científicamente diseñada para personas con diabetes y pre-diabetes. Contiene un sistema ...',
    nombreProducto: 'Glucerna Triple Care x 900 g',
    stock: '1000',
    etiquetas: 'No',
    precio: 119.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/16.jpg`,
    idCategoria: 'null',
  },
  //producto 17 
  {
    descripcion: 'OFS® es un suplemento nutricional con nutrientes que ayudan a fortalecer el sistema ...',
    nombreProducto: 'OFS Suplemento Nutricional Optimun Food Support x 440 g',
    stock: '1000',
    etiquetas: 'No',
    precio: 105.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/17.jpg`,
    idCategoria: 'null',
  },
  //producto 18 
  {
    descripcion: 'La más completa fórmula 4 en 1 que ayuda a mantener sanas las articulaciones. Coadyuvante en el tratamiento de la artrosis leve a moderada con accion condrotrofica.',
    nombreProducto: 'Finartrit Advanced x 30 Sobres',
    stock: '1000',
    etiquetas: 'No',
    precio: 120.20,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/18.jpg`,
    idCategoria: 'null',
  },
  //producto 19 
  {
    descripcion: 'Complemento nutricional en polvo para preparar bebida, hecho sobre la base de proteína de soya, vitaminas y minerales.',
    nombreProducto: 'Ensoy NF Lata x 1kg + Lata Vainilla x 400g',
    stock: '1000',
    etiquetas: 'No',
    precio: 93.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/19.jpg`,
    idCategoria: 'null',
  },
  //producto 20
  {
    descripcion: 'HIDROLÁGENOQ10 es un suplemento alimenticio cuya formulación contiene antioxidantes, vitamina, Q10 y colageno  ...',
    nombreProducto: 'Hidrolágeno Q10 x 30 Sobres',
    stock: '1000',
    etiquetas: 'No',
    precio: 114.20,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/20.jpg`,
    idCategoria: 'null',
  },
  //producto 21 
  {
    descripcion: 'La vitamina B12 contribuye a la formación normal de glóbulos rojos, al funcionamiento normal ...',
    nombreProducto: 'Vitamina B12 Mason 1000 mcg x 100 Tabletas',
    stock: '1000',
    etiquetas: 'No',
    precio: 79.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/21.jpg`,
    idCategoria: 'null',
  },
  //producto 22 
  {
    descripcion: 'Debido a su alto contenido de proteínas y nutrientes, la levadura de cerveza ayuda a mantener la tonicidad muscular. Fórmula ...',
    nombreProducto: 'Levadura de Cerveza y Bayas de Goji Vid Natur x 100 Tabletas',
    stock: '1000',
    etiquetas: 'No',
    precio: 29.10,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/22.jpg`,
    idCategoria: 'null',
  },
  //producto 23 
  {
    descripcion: 'Mide el nivel de concentración de oxigeno en la sangre. Especialmente indicado en personas con insuficiencia cardiaca, enfermedades pulmonares obstructivas ...',
    nombreProducto: 'Oximetro de Dedo Contec',
    stock: '1000',
    etiquetas: 'No',
    precio: 90.80,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/23.jpg`,
    idCategoria: 'null',
  },
  //producto 24 
  {
    descripcion: 'Este instrumento debe usarse únicamente para medir la temperatura corporal, Evite someter el instrumento a una temperatura ambiente superior a 60 °C.',
    nombreProducto: 'Termómetro Digital Microlife Pen MT3001',
    stock: '1000',
    etiquetas: 'No',
    precio: 28.10,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/24.jpg`,
    idCategoria: 'null',
  },
  //producto 25 
  {
    descripcion: 'Medición sin contacto con la piel. Medición sencilla y rápida (1 segundo). Toma de medida ...',
    nombreProducto: 'Termómetro Sin Contacto BBLove-AET R1D1',
    stock: '1000',
    etiquetas: 'No',
    precio: 91.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/25.jpg`,
    idCategoria: 'null',
  },
  //producto 26 
  {
    descripcion: 'Resultado en 5 segundos,Mínimo volumen de muestra,Pantalla LCD de gran tamaño,Precisión ...',
    nombreProducto: 'Medidor de Glucosa Exactive Vital Kit',
    stock: '1000',
    etiquetas: 'No',
    precio: 155.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/26.jpg`,
    idCategoria: 'null',
  },
  //producto 27 
   {
    descripcion: 'Antifaz para dormir cómodo, ópaco incluye tapones auditivos de espuma',
    nombreProducto: 'Cover Antifaz + Tapones',
    stock: '1000',
    etiquetas: 'No',
    precio: 19.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/27.jpg`,
    idCategoria: 'null',
   },
    //producto 28 
    {
    descripcion: 'Fórmula con activos hidratantes ...',
    nombreProducto: 'Desodorante en Spray Nivea Black & White Toque de Seda x 150 ml',
    stock: '1000',
    etiquetas: 'No',
    precio: 15.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/28.jpg`,
    idCategoria: 'null',
    },
  //producto 29 
   {
    descripcion: 'Fotoprotector de amplio espectro ...',
    nombreProducto: 'Fotoprotector Umbrella Gel SPF 50+ x 60 g',
    stock: '1000',
    etiquetas: 'No',
    precio: 69.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/29.jpg`,
    idCategoria: 'null',
   },
  //producto 30 
   {
    descripcion: 'Guante Quirúrgico estéril 7',
    nombreProducto: 'Guante Quirúrgico Estéril 7 x 1 Par',
    stock: '1000',
    etiquetas: 'No',
    precio: 2.30,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/30.jpg`,
    idCategoria: 'null',
   },
   //producto 31 
   {
    descripcion: '365 días de uso, 110 lavadas (lavar cada 3 a 4 días), 5 capas de filtración 99.99%), tecnología de auto ...',
    nombreProducto: 'Mascarilla con Válvula Eco Air Mask Talla M Negro x 1 Unidad',
    stock: '1000',
    etiquetas: 'No',
    precio: 65.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/31.jpg`,
    idCategoria: 'null',
   },
   //producto 32 
   {
    descripcion: 'Altamente respirable,almohadilla antiadherente,adhesivo suave e hipoalergénico.',
    nombreProducto: 'Parche Ocular Opticlude Nexcare para Adultos x 20 Unidades',
    stock: '1000',
    etiquetas: 'No',
    precio: 52.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/32.jpg`,
    idCategoria: 'null',
   },
   //producto 33 
   {
    descripcion: 'FOOT WORKS® – Moleskin parches recortables, es una almohadilla adhesiva recortable, ultrasuave ...',
    nombreProducto: 'Parches Recortables para Pies Foot Works Moleskin x 4 Unidades',
    stock: '1000',
    etiquetas: 'No',
    precio: 35.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/33.jpg`,
    idCategoria: 'null',
   },
   //producto 34 
   {
    descripcion: 'Contravaris, es un medicamento natural a base de Ruscus aculeatus, de Laboratorios Garden ...',
    nombreProducto: 'Contravaris 100mg x 60 Cápsulas',
    stock: '1000',
    etiquetas: 'No',
    precio: 61.10,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/34.jpg`,
    idCategoria: 'null',
   },
   //producto 35 
   {
    descripcion: 'Antiséptico y desinfectante para piel y superfies. Concentración alcoholica recomendada para usos medicinales.',
    nombreProducto: 'Alkofarma Alcohol Medicinal 70° x 120 ml',
    stock: '1000',
    etiquetas: 'No',
    precio: 3.30,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/35.jpg`,
    idCategoria: 'null',
   },
   //producto 36 
   {
    descripcion: 'Para su uso en la limpieza diaria, la eliminación de depósitos de proteínas, enjuague, humectación, desinfección ...',
    nombreProducto: 'Solución para Lentes de Contacto Opti-Free x 120 ml',
    stock: '1000',
    etiquetas: 'No',
    precio: 22.50,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/36.jpg`,
    idCategoria: 'null',
   },
   //producto 37 
   {
    descripcion: 'Tiene una cubierta especial, que asegura ...',
    nombreProducto: 'Dulcolax 5 mg x 20 Tabletas',
    stock: '1000',
    etiquetas: 'No',
    precio: 21.00,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/37.jpg`,
    idCategoria: 'null',
   },
   //producto 38 
   {
    descripcion: 'Cinta Quirúrgica de papel ideal ...',
    nombreProducto: 'Cinta Quirúrgica de Papel Micropore Nexcare 2.5 cm x 9.1 m',
    stock: '1000',
    etiquetas: 'No',
    precio: 15.50,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/38.jpg`,
    idCategoria: 'null',
   },
   //producto 39
   {
    descripcion: 'Almacenador de pastillas.',
    nombreProducto: 'Pastillero 28 Casilleros x 1 Unidad',
    stock: '1000',
    etiquetas: 'No',
    precio: 19.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/39.jpg`,
    idCategoria: 'null',
   },
   //producto 40
   {
    descripcion: 'INSULINA GLARGINA 100 U/mL y LIXISENATIDA 33 μg/mL SoloStar Solución inyectable, en pluma (aplicador) prellenada descartable',
    nombreProducto: 'Soliqua (30-60) Solución Inyectable',
    stock: '1000',
    etiquetas: 'No',
    precio: 212.90,
    tipoProducto: 'salud',
    requiereReceta: 'No',
    imgSrc: `/assets/images/productos/39.jpg`,
    idCategoria: 'null',
   },
];
